# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get neighborhood of a pixel in a 3D image
#'
#' This function returns the neighborhood of a pixel in a 3D image. Returns the
#' 8 neighboring (plus center pixel) for the pixel at row and col. The input
#' \code{img} is a three-dimensional array containing the image data.
#'
#' @param row An integer representing the row index of the pixel of interest.
#' @param col An integer representing the column index of the pixel of interest.
#' @param img A cube object containing the image data.
#'
#' @return A matrix representing the neighborhood of the pixel of interest.
#'
#' @export
#' @name get_neigh
#'
#' @examples
#' img <- array(1:27, dim = c(3, 3, 3))
#' get_neigh(2, 2, img)
#'
get_neigh <- function(row, col, img) {
    .Call(`_SpecAI_Seg_get_neigh`, row, col, img)
}

#' Calculates RCMG using Euclidean distance
#'
#' For every pixel, find the RCMG where the 8 neighboring pixels make up the
#' pairwise distance matrix, and r is the number of pairs of pixels to remove.
#' Don't set r larger than 3.
#'
#' @param img A 3D cube containing the image data
#' @param r An integer specifying the radius of the rolling window
#'
#' @return A matrix containing the Euclidean distances of the pixels
#'
#' @export
#' @name rcmg_euclid
rcmg_euclid <- function(img, r = 1L) {
    .Call(`_SpecAI_Seg_rcmg_euclid`, img, r)
}

#' Calculates RCMG using Euclidean distance
#'
#' For every pixel, find the RCMG where the 8 neighboring pixels make up the
#' pairwise distance matrix, and r is the number of pairs of pixels to remove.
#' Don't set r larger than 3.
#'
#' @param img A 3D cube containing the image data
#' @param r An integer specifying the radius of the rolling window
#'
#' @return A matrix containing the Euclidean distances of the pixels
#'
#' @export
#' @name rcmg_cos
rcmg_cos <- function(img, r = 1L) {
    .Call(`_SpecAI_Seg_rcmg_cos`, img, r)
}

#' Relabels segmentation
#'
#' Relabels segmentation map starting the labeling at 1.
#'
#' @param seg a segmentation matrix to relabel.
#'
#' @return relabeled matrix.
#'
#' @export
#' @name relabel_seg
#'
relabel_seg <- function(seg) {
    .Call(`_SpecAI_Seg_relabel_seg`, seg)
}

