# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
get_neigh <- function(row, col, img) {
    .Call(`_SpecAI_Seg_get_neigh`, row, col, img)
}

#' @export
rcmg_euclid <- function(img, r = 1L) {
    .Call(`_SpecAI_Seg_rcmg_euclid`, img, r)
}

#' @export
rcmg_cos <- function(img, r = 1L) {
    .Call(`_SpecAI_Seg_rcmg_cos`, img, r)
}

